version: "3.6"
services:
    php:
        build:
            context: .
            target: php
            # args:
                # - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:80
            - 5173:5173
        networks:
            - default
        depends_on:
            - redis-server
        tty: true
    redis-server:
        image: redis:latest
        command: redis-server --requirepass "${REDIS_PASSWORD}"
        ports:
            - 6379:6379
networks:
    default:
        driver: bridge
volumes:
    db-data: ~

