version: "3.0"
services:
    php:
        build:
            context: .
            target: php
            # args:
                # - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:80
        networks:
            - default
    # db:
    #     image: mysql:8.0
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    #         - MYSQL_USER=${DB_USERNAME}
    #         - MYSQL_PASSWORD=${DB_PASSWORD}
    #         - MYSQL_DATABASE=${DB_DATABASE}
    #     volumes:
    #         - db-data:/var/lib/mysql
    #     ports:
    #         - 3307:3306
    # phpmyadmin:
    #     depends_on:
    #         - db
    #     image: phpmyadmin
    #     ports:
    #         - "8090:80"
    #     environment:
    #         PMA_HOST: db
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
networks:
    default:
        driver: bridge
volumes:
    db-data: ~

